-- ==========================================
-- KETABINO SQLITE DATABASE SCHEMA DDL
-- ==========================================

-- 1. USERS Table
CREATE TABLE USERS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PHONE_NUMBER TEXT UNIQUE NOT NULL,
    NAME TEXT NOT NULL,
    ROLE TEXT DEFAULT 'Reader' NOT NULL, -- 'Reader', 'Author', 'Admin'
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 2. AUTHOR_PROFILES Table
CREATE TABLE AUTHOR_PROFILES (
    USER_ID INTEGER PRIMARY KEY,
    BIO TEXT,
    PROFILE_IMAGE TEXT,
    SOCIAL_LINKS TEXT,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- 3. WALLETS Table
CREATE TABLE WALLETS (
    USER_ID INTEGER PRIMARY KEY,
    BALANCE REAL DEFAULT 0.00 NOT NULL,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- 4. BOOKS Table
CREATE TABLE BOOKS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    AUTHOR_ID INTEGER NOT NULL,
    TITLE TEXT NOT NULL,
    DESCRIPTION TEXT,
    COVER_IMAGE TEXT,
    STATUS TEXT DEFAULT 'Draft' NOT NULL, -- 'Draft', 'Published', 'Archived'
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (AUTHOR_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- 5. CHAPTERS Table
CREATE TABLE CHAPTERS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    BOOK_ID INTEGER NOT NULL,
    TITLE TEXT NOT NULL,
    CONTENT TEXT NOT NULL,
    SEQUENCE_NUMBER INTEGER NOT NULL,
    PRICE REAL DEFAULT 0.00 NOT NULL,
    IS_FREE INTEGER DEFAULT 0 NOT NULL, -- 0 = False, 1 = True
    STATUS TEXT DEFAULT 'Draft' NOT NULL, -- 'Draft', 'Published'
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(ID) ON DELETE CASCADE,
    UNIQUE (BOOK_ID, SEQUENCE_NUMBER)
);

-- 6. GENRES Table
CREATE TABLE GENRES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT UNIQUE NOT NULL
);

-- 7. BOOK_GENRES Table
CREATE TABLE BOOK_GENRES (
    BOOK_ID INTEGER NOT NULL,
    GENRE_ID INTEGER NOT NULL,
    PRIMARY KEY (BOOK_ID, GENRE_ID),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(ID) ON DELETE CASCADE,
    FOREIGN KEY (GENRE_ID) REFERENCES GENRES(ID) ON DELETE CASCADE
);

-- 8. COIN_PACKAGES Table
CREATE TABLE COIN_PACKAGES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    COINS INTEGER NOT NULL,
    PRICE REAL NOT NULL,
    IS_ACTIVE INTEGER DEFAULT 1 NOT NULL
);

-- 9. TRANSACTIONS Table
CREATE TABLE TRANSACTIONS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    AMOUNT REAL NOT NULL,
    TYPE TEXT NOT NULL, -- 'Deposit', 'Withdrawal', 'Purchase', 'Refund'
    DESCRIPTION TEXT,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- 10. PURCHASES Table
CREATE TABLE PURCHASES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    CHAPTER_ID INTEGER NOT NULL,
    PRICE_PAID REAL NOT NULL,
    PURCHASED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (CHAPTER_ID) REFERENCES CHAPTERS(ID) ON DELETE CASCADE,
    UNIQUE (USER_ID, CHAPTER_ID)
);

-- 11. READING_PROGRESS Table
CREATE TABLE READING_PROGRESS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    BOOK_ID INTEGER NOT NULL,
    LAST_READ_CHAPTER_ID INTEGER,
    LAST_READ_POSITION INTEGER DEFAULT 0,
    LAST_READ_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(ID) ON DELETE CASCADE,
    FOREIGN KEY (LAST_READ_CHAPTER_ID) REFERENCES CHAPTERS(ID) ON DELETE SET NULL,
    UNIQUE (USER_ID, BOOK_ID)
);

-- 12. BOOKMARKS Table
CREATE TABLE BOOKMARKS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    CHAPTER_ID INTEGER NOT NULL,
    POSITION INTEGER NOT NULL,
    NOTE TEXT,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (CHAPTER_ID) REFERENCES CHAPTERS(ID) ON DELETE CASCADE
);

-- 13. HIGHLIGHTS Table
CREATE TABLE HIGHLIGHTS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    CHAPTER_ID INTEGER NOT NULL,
    START_CHAR INTEGER NOT NULL,
    END_CHAR INTEGER NOT NULL,
    COLOR TEXT NOT NULL,
    TEXT_CONTENT TEXT NOT NULL,
    NOTE TEXT,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (CHAPTER_ID) REFERENCES CHAPTERS(ID) ON DELETE CASCADE
);

-- 14. REVIEWS Table
CREATE TABLE REVIEWS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    BOOK_ID INTEGER NOT NULL,
    RATING INTEGER NOT NULL CHECK (RATING >= 1 AND RATING <= 5),
    TITLE TEXT,
    CONTENT TEXT,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(ID) ON DELETE CASCADE,
    UNIQUE (USER_ID, BOOK_ID)
);

-- 15. COMMENTS Table
CREATE TABLE COMMENTS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    BOOK_ID INTEGER NOT NULL,
    CHAPTER_ID INTEGER,
    PARENT_COMMENT_ID INTEGER,
    CONTENT TEXT NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(ID) ON DELETE CASCADE,
    FOREIGN KEY (CHAPTER_ID) REFERENCES CHAPTERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (PARENT_COMMENT_ID) REFERENCES COMMENTS(ID) ON DELETE CASCADE
);

-- 16. SUBSCRIPTION_PLANS Table
CREATE TABLE SUBSCRIPTION_PLANS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    PRICE REAL NOT NULL,
    DURATION_DAYS INTEGER NOT NULL,
    DESCRIPTION TEXT,
    IS_ACTIVE INTEGER DEFAULT 1 NOT NULL
);

-- 17. USER_SUBSCRIPTIONS Table
CREATE TABLE USER_SUBSCRIPTIONS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    PLAN_ID INTEGER NOT NULL,
    START_DATE DATETIME NOT NULL,
    END_DATE DATETIME NOT NULL,
    STATUS TEXT DEFAULT 'Active' NOT NULL, -- 'Active', 'Expired', 'Cancelled'
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (PLAN_ID) REFERENCES SUBSCRIPTION_PLANS(ID) ON DELETE CASCADE
);

-- 18. LIKES Table
CREATE TABLE LIKES (
    USER_ID INTEGER NOT NULL,
    BOOK_ID INTEGER NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (USER_ID, BOOK_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(ID) ON DELETE CASCADE
);

-- 19. NOTIFICATIONS Table
CREATE TABLE NOTIFICATIONS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    TITLE TEXT NOT NULL,
    MESSAGE TEXT NOT NULL,
    TYPE TEXT DEFAULT 'System' NOT NULL, -- 'System', 'BookUpdate', 'CommentReply'
    IS_READ INTEGER DEFAULT 0 NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- 20. WRITER_STUDIO_ASSETS Table
CREATE TABLE WRITER_STUDIO_ASSETS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    AUTHOR_ID INTEGER NOT NULL,
    BOOK_ID INTEGER,
    ASSET_TYPE TEXT NOT NULL, -- 'CoverImage', 'ChapterImage', 'Resource'
    FILE_PATH TEXT NOT NULL,
    FILE_SIZE INTEGER NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (AUTHOR_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(ID) ON DELETE CASCADE
);

-- 21. REPORTS Table
CREATE TABLE REPORTS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    TARGET_TYPE TEXT NOT NULL, -- 'Book', 'Chapter', 'Comment'
    TARGET_ID INTEGER NOT NULL,
    REASON TEXT NOT NULL,
    DESCRIPTION TEXT,
    STATUS TEXT DEFAULT 'Pending' NOT NULL, -- 'Pending', 'Resolved', 'Dismissed'
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);
